// src/api/client.ts
import createClient from 'openapi-fetch'
import type { paths } from '../types/api' // Generated by openapi-typescript

export const api = createClient<paths>({
  baseUrl: '/api',
})
